services:
  app:
    container_name: nrb-app
    build:
      context: . 
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
    depends_on: 
      - redis 
      - mysql
    networks: 
      - app
  mysql:
    container_name: nrb-db
    image: 'mysql:8.0'
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'db:/docker-entrypoint-initdb.d'
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASS}"]
  redis:
    container_name: nrb-redis
    image: "redis:alpine" 
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  selenium:
    container_name: nrb-selenium
    image: 'selenium/standalone-chrome'
    ports:
      - '${SELENIUM_PORT:-4000}:4444'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - app

volumes:
  redis:
    driver: local
  db:
    driver: local

networks:
  app:    
    driver: bridge
